const data = [
  {
    key: '1',
    firstName: 'John',
    lastName: 'Brown',
    age: 32,
    city: 'Oslo',
    cb: 'Ukraine',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    tags: ['k'],
    description: 'Some about person',
  },
  {
    key: '2',
    firstName: 'Jim',
    lastName: 'Green',
    age: 42,
    cb: 'Romania',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'w',
    city: 'Bergen',
    tags: ['t'],
    description: 'Some about person',
  },
  {
    key: '3',
    firstName: 'Joe',
    lastName: 'Black',
    age: 32,
    cb: 'East Europe',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    city: 'Lillehammer',
    tags: ['g'],
    description: 'Some about person',
  },
  {
    key: '4',
    firstName: 'John',
    lastName: 'Brown',
    age: 32,
    city: 'Oslo',
    cb: 'Ukraine',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    tags: ['k'],
    description: 'Some about person',
  },
  {
    key: '5',
    firstName: 'Jim',
    lastName: 'Green',
    age: 42,
    cb: 'Romania',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'w',
    city: 'Bergen',
    tags: ['t'],
    description: 'Some about person',
  },
  {
    key: '6',
    firstName: 'Joe',
    lastName: 'Black',
    age: 32,
    cb: 'East Europe',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    city: 'Lillehammer',
    tags: ['g'],
    description: 'Some about person',
  },
  {
    key: '7',
    firstName: 'John',
    lastName: 'Brown',
    age: 32,
    city: 'Oslo',
    cb: 'Ukraine',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    tags: ['k'],
    description: 'Some about person',
  },
  {
    key: '8',
    firstName: 'Jim',
    lastName: 'Green',
    age: 42,
    cb: 'Romania',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'w',
    city: 'Bergen',
    tags: ['t'],
    description: 'Some about person',
  },
  {
    key: '9',
    firstName: 'Joe',
    lastName: 'Black',
    age: 32,
    cb: 'East Europe',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    city: 'Lillehammer',
    tags: ['g'],
    description: 'Some about person',
  },
  {
    key: '10',
    firstName: 'John',
    lastName: 'Brown',
    age: 32,
    city: 'Oslo',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    cb: 'Ukraine',
    gender: 'm',
    tags: ['k'],

  },
  {
    key: '11',
    firstName: 'Jim',
    lastName: 'Green',
    age: 42,
    cb: 'Romania',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'w',
    city: 'Bergen',
    tags: ['t'],
  },
  {
    key: '12',
    firstName: 'Joe',
    lastName: 'Black',
    age: 32,
    cb: 'East Europe',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    city: 'Lillehammer',
    tags: ['g'],
  },
  {
    key: '1',
    firstName: 'John',
    lastName: 'Brown',
    age: 32,
    city: 'Oslo',
    cb: 'Ukraine',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    tags: ['k'],
    description: 'Some about person',
  },
  {
    key: '2',
    firstName: 'Jim',
    lastName: 'Green',
    age: 42,
    cb: 'Romania',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'w',
    city: 'Bergen',
    tags: ['t'],
    description: 'Some about person',
  },
  {
    key: '3',
    firstName: 'Joe',
    lastName: 'Black',
    age: 32,
    cb: 'East Europe',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    city: 'Lillehammer',
    tags: ['g'],
    description: 'Some about person',
  },
  {
    key: '4',
    firstName: 'John',
    lastName: 'Brown',
    age: 32,
    city: 'Oslo',
    cb: 'Ukraine',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    tags: ['k'],
    description: 'Some about person',
  },
  {
    key: '5',
    firstName: 'Jim',
    lastName: 'Green',
    age: 42,
    cb: 'Romania',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'w',
    city: 'Bergen',
    tags: ['t'],
    description: 'Some about person',
  },
  {
    key: '6',
    firstName: 'Joe',
    lastName: 'Black',
    age: 32,
    cb: 'East Europe',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    city: 'Lillehammer',
    tags: ['g'],
    description: 'Some about person',
  },
  {
    key: '7',
    firstName: 'John',
    lastName: 'Brown',
    age: 32,
    city: 'Oslo',
    cb: 'Ukraine',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    tags: ['k'],
    description: 'Some about person',
  },
  {
    key: '8',
    firstName: 'Jim',
    lastName: 'Green',
    age: 42,
    cb: 'Romania',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'w',
    city: 'Bergen',
    tags: ['t'],
    description: 'Some about person',
  },
  {
    key: '9',
    firstName: 'Joe',
    lastName: 'Black',
    age: 32,
    cb: 'East Europe',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    city: 'Lillehammer',
    tags: ['g'],
    description: 'Some about person',
  },
  {
    key: '10',
    firstName: 'John',
    lastName: 'Brown',
    age: 32,
    city: 'Oslo',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    cb: 'Ukraine',
    gender: 'm',
    tags: ['k'],

  },
  {
    key: '11',
    firstName: 'Jim',
    lastName: 'Green',
    age: 42,
    cb: 'Romania',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'w',
    city: 'Bergen',
    tags: ['t'],
  },
  {
    key: '12',
    firstName: 'Joe',
    lastName: 'Black',
    age: 32,
    cb: 'East Europe',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    city: 'Lillehammer',
    tags: ['g'],
  },
  {
    key: '1',
    firstName: 'John',
    lastName: 'Brown',
    age: 32,
    city: 'Oslo',
    cb: 'Ukraine',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    tags: ['k'],
    description: 'Some about person',
  },
  {
    key: '2',
    firstName: 'Jim',
    lastName: 'Green',
    age: 42,
    cb: 'Romania',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'w',
    city: 'Bergen',
    tags: ['t'],
    description: 'Some about person',
  },
  {
    key: '3',
    firstName: 'Joe',
    lastName: 'Black',
    age: 32,
    cb: 'East Europe',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    city: 'Lillehammer',
    tags: ['g'],
    description: 'Some about person',
  },
  {
    key: '4',
    firstName: 'John',
    lastName: 'Brown',
    age: 32,
    city: 'Oslo',
    cb: 'Ukraine',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    tags: ['k'],
    description: 'Some about person',
  },
  {
    key: '5',
    firstName: 'Jim',
    lastName: 'Green',
    age: 42,
    cb: 'Romania',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'w',
    city: 'Bergen',
    tags: ['t'],
    description: 'Some about person',
  },
  {
    key: '6',
    firstName: 'Joe',
    lastName: 'Black',
    age: 32,
    cb: 'East Europe',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    city: 'Lillehammer',
    tags: ['g'],
    description: 'Some about person',
  },
  {
    key: '7',
    firstName: 'John',
    lastName: 'Brown',
    age: 32,
    city: 'Oslo',
    cb: 'Ukraine',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    tags: ['k'],
    description: 'Some about person',
  },
  {
    key: '8',
    firstName: 'Jim',
    lastName: 'Green',
    age: 42,
    cb: 'Romania',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'w',
    city: 'Bergen',
    tags: ['t'],
    description: 'Some about person',
  },
  {
    key: '9',
    firstName: 'Joe',
    lastName: 'Black',
    age: 32,
    cb: 'East Europe',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    city: 'Lillehammer',
    tags: ['g'],
    description: 'Some about person',
  },
  {
    key: '10',
    firstName: 'John',
    lastName: 'Brown',
    age: 32,
    city: 'Oslo',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    cb: 'Ukraine',
    gender: 'm',
    tags: ['k'],

  },
  {
    key: '11',
    firstName: 'Jim',
    lastName: 'Green',
    age: 42,
    cb: 'Romania',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'w',
    city: 'Bergen',
    tags: ['t'],
  },
  {
    key: '12',
    firstName: 'Joe',
    lastName: 'Black',
    age: 32,
    cb: 'East Europe',
    email: 'john.brown@gmai.com',
    phone:'+479898989898',
    gender: 'm',
    city: 'Lillehammer',
    tags: ['g'],
  },
];

export default data